#include "cslugify.h"
#include <string.h>
#include <wchar.h>
#include <wctype.h>

static const CharMapEntry charMap[MAX_CHAR_MAP] = {
    {L'$', "dollar"},
    {L'%', "percent"},
    {L'&', "and"},
    {L'<', "less"},
    {L'>', "greater"},
    {L'|', "or"},
    {L'¢', "cent"},
    {L'£', "pound"},
    {L'¤', "currency"},
    {L'¥', "yen"},
    {L'©', "(c)"},
    {L'ª', "a"},
    {L'®', "(r)"},
    {L'º', "o"},
    {L'À', "A"},
    {L'Á', "A"},
    {L'Â', "A"},
    {L'Ã', "A"},
    {L'Ä', "A"},
    {L'Å', "A"},
    {L'Æ', "AE"},
    {L'Ç', "C"},
    {L'È', "E"},
    {L'É', "E"},
    {L'Ê', "E"},
    {L'Ë', "E"},
    {L'Ì', "I"},
    {L'Í', "I"},
    {L'Î', "I"},
    {L'Ï', "I"},
    {L'Ð', "D"},
    {L'Ñ', "N"},
    {L'Ò', "O"},
    {L'Ó', "O"},
    {L'Ô', "O"},
    {L'Õ', "O"},
    {L'Ö', "O"},
    {L'Ø', "O"},
    {L'Ù', "U"},
    {L'Ú', "U"},
    {L'Û', "U"},
    {L'Ü', "U"},
    {L'Ý', "Y"},
    {L'Þ', "TH"},
    {L'ß', "ss"},
    {L'à', "a"},
    {L'á', "a"},
    {L'â', "a"},
    {L'ã', "a"},
    {L'ä', "a"},
    {L'å', "a"},
    {L'æ', "ae"},
    {L'ç', "c"},
    {L'è', "e"},
    {L'é', "e"},
    {L'ê', "e"},
    {L'ë', "e"},
    {L'ì', "i"},
    {L'í', "i"},
    {L'î', "i"},
    {L'ï', "i"},
    {L'ð', "d"},
    {L'ñ', "n"},
    {L'ò', "o"},
    {L'ó', "o"},
    {L'ô', "o"},
    {L'õ', "o"},
    {L'ö', "o"},
    {L'ø', "o"},
    {L'ù', "u"},
    {L'ú', "u"},
    {L'û', "u"},
    {L'ü', "u"},
    {L'ý', "y"},
    {L'þ', "th"},
    {L'ÿ', "y"},
    {L'Ā', "A"},
    {L'ā', "a"},
    {L'Ă', "A"},
    {L'ă', "a"},
    {L'Ą', "A"},
    {L'ą', "a"},
    {L'Ć', "C"},
    {L'ć', "c"},
    {L'Č', "C"},
    {L'č', "c"},
    {L'Ď', "D"},
    {L'ď', "d"},
    {L'Đ', "DJ"},
    {L'đ', "dj"},
    {L'Ē', "E"},
    {L'ē', "e"},
    {L'Ė', "E"},
    {L'ė', "e"},
    {L'Ę', "e"},
    {L'ę', "e"},
    {L'Ě', "E"},
    {L'ě', "e"},
    {L'Ğ', "G"},
    {L'ğ', "g"},
    {L'Ģ', "G"},
    {L'ģ', "g"},
    {L'Ĩ', "I"},
    {L'ĩ', "i"},
    {L'Ī', "i"},
    {L'ī', "i"},
    {L'Į', "I"},
    {L'į', "i"},
    {L'İ', "I"},
    {L'ı', "i"},
    {L'Ķ', "k"},
    {L'ķ', "k"},
    {L'Ļ', "L"},
    {L'ļ', "l"},
    {L'Ľ', "L"},
    {L'ľ', "l"},
    {L'Ł', "L"},
    {L'ł', "l"},
    {L'Ń', "N"},
    {L'ń', "n"},
    {L'Ņ', "N"},
    {L'ņ', "n"},
    {L'Ň', "N"},
    {L'ň', "n"},
    {L'Ō', "O"},
    {L'ō', "o"},
    {L'Ő', "O"},
    {L'ő', "o"},
    {L'Œ', "OE"},
    {L'œ', "oe"},
    {L'Ŕ', "R"},
    {L'ŕ', "r"},
    {L'Ř', "R"},
    {L'ř', "r"},
    {L'Ś', "S"},
    {L'ś', "s"},
    {L'Ş', "S"},
    {L'ş', "s"},
    {L'Š', "S"},
    {L'š', "s"},
    {L'Ţ', "T"},
    {L'ţ', "t"},
    {L'Ť', "T"},
    {L'ť', "t"},
    {L'Ũ', "U"},
    {L'ũ', "u"},
    {L'Ū', "u"},
    {L'ū', "u"},
    {L'Ů', "U"},
    {L'ů', "u"},
    {L'Ű', "U"},
    {L'ű', "u"},
    {L'Ų', "U"},
    {L'ų', "u"},
    {L'Ŵ', "W"},
    {L'ŵ', "w"},
    {L'Ŷ', "Y"},
    {L'ŷ', "y"},
    {L'Ÿ', "Y"},
    {L'Ź', "Z"},
    {L'ź', "z"},
    {L'Ż', "Z"},
    {L'ż', "z"},
    {L'Ž', "Z"},
    {L'ž', "z"},
    {L'Ə', "E"},
    {L'ƒ', "f"},
    {L'Ơ', "O"},
    {L'ơ', "o"},
    {L'Ư', "U"},
    {L'ư', "u"},
    {L'ǈ', "LJ"},
    {L'ǉ', "lj"},
    {L'ǋ', "NJ"},
    {L'ǌ', "nj"},
    {L'Ș', "S"},
    {L'ș', "s"},
    {L'Ț', "T"},
    {L'ț', "t"},
    {L'ə', "e"},
    {L'˚', "o"},
    {L'Ά', "A"},
    {L'Έ', "E"},
    {L'Ή', "H"},
    {L'Ί', "I"},
    {L'Ό', "O"},
    {L'Ύ', "Y"},
    {L'Ώ', "W"},
    {L'ΐ', "i"},
    {L'Α', "A"},
    {L'Β', "B"},
    {L'Γ', "G"},
    {L'Δ', "D"},
    {L'Ε', "E"},
    {L'Ζ', "Z"},
    {L'Η', "H"},
    {L'Θ', "8"},
    {L'Ι', "I"},
    {L'Κ', "K"},
    {L'Λ', "L"},
    {L'Μ', "M"},
    {L'Ν', "N"},
    {L'Ξ', "3"},
    {L'Ο', "O"},
    {L'Π', "P"},
    {L'Ρ', "R"},
    {L'Σ', "S"},
    {L'Τ', "T"},
    {L'Υ', "Y"},
    {L'Φ', "F"},
    {L'Χ', "X"},
    {L'Ψ', "PS"},
    {L'Ω', "W"},
    {L'Ϊ', "I"},
    {L'Ϋ', "Y"},
    {L'ά', "a"},
    {L'έ', "e"},
    {L'ή', "h"},
    {L'ί', "i"},
    {L'ΰ', "y"},
    {L'α', "a"},
    {L'β', "b"},
    {L'γ', "g"},
    {L'δ', "d"},
    {L'ε', "e"},
    {L'ζ', "z"},
    {L'η', "h"},
    {L'θ', "8"},
    {L'ι', "i"},
    {L'κ', "k"},
    {L'λ', "l"},
    {L'μ', "m"},
    {L'ν', "n"},
    {L'ξ', "3"},
    {L'ο', "o"},
    {L'π', "p"},
    {L'ρ', "r"},
    {L'ς', "s"},
    {L'σ', "s"},
    {L'τ', "t"},
    {L'υ', "y"},
    {L'φ', "f"},
    {L'χ', "x"},
    {L'ψ', "ps"},
    {L'ω', "w"},
    {L'ϊ', "i"},
    {L'ϋ', "y"},
    {L'ό', "o"},
    {L'ύ', "y"},
    {L'ώ', "w"},
    {L'Ё', "Yo"},
    {L'Ђ', "DJ"},
    {L'Є', "Ye"},
    {L'І', "I"},
    {L'Ї', "Yi"},
    {L'Ј', "J"},
    {L'Љ', "LJ"},
    {L'Њ', "NJ"},
    {L'Ћ', "C"},
    {L'Џ', "DZ"},
    {L'А', "A"},
    {L'Б', "B"},
    {L'В', "V"},
    {L'Г', "G"},
    {L'Д', "D"},
    {L'Е', "E"},
    {L'Ж', "Zh"},
    {L'З', "Z"},
    {L'И', "I"},
    {L'Й', "J"},
    {L'К', "K"},
    {L'Л', "L"},
    {L'М', "M"},
    {L'Н', "N"},
    {L'О', "O"},
    {L'П', "P"},
    {L'Р', "R"},
    {L'С', "S"},
    {L'Т', "T"},
    {L'У', "U"},
    {L'Ф', "F"},
    {L'Х', "H"},
    {L'Ц', "C"},
    {L'Ч', "Ch"},
    {L'Ш', "Sh"},
    {L'Щ', "Sh"},
    {L'Ъ', "U"},
    {L'Ы', "Y"},
    {L'Ь', ""},
    {L'Э', "E"},
    {L'Ю', "Yu"},
    {L'Я', "Ya"},
    {L'а', "a"},
    {L'б', "b"},
    {L'в', "v"},
    {L'г', "g"},
    {L'д', "d"},
    {L'е', "e"},
    {L'ж', "zh"},
    {L'з', "z"},
    {L'и', "i"},
    {L'й', "j"},
    {L'к', "k"},
    {L'л', "l"},
    {L'м', "m"},
    {L'н', "n"},
    {L'о', "o"},
    {L'п', "p"},
    {L'р', "r"},
    {L'с', "s"},
    {L'т', "t"},
    {L'у', "u"},
    {L'ф', "f"},
    {L'х', "h"},
    {L'ц', "c"},
    {L'ч', "ch"},
    {L'ш', "sh"},
    {L'щ', "sh"},
    {L'ъ', "u"},
    {L'ы', "y"},
    {L'ь', ""},
    {L'э', "e"},
    {L'ю', "yu"},
    {L'я', "ya"},
    {L'ё', "yo"},
    {L'ђ', "dj"},
    {L'є', "ye"},
    {L'і', "i"},
    {L'ї', "yi"},
    {L'ј', "j"},
    {L'љ', "lj"},
    {L'њ', "nj"},
    {L'ћ', "c"},
    {L'ѝ', "u"},
    {L'џ', "dz"},
    {L'Ґ', "G"},
    {L'ґ', "g"},
    {L'Ғ', "GH"},
    {L'ғ', "gh"},
    {L'Қ', "KH"},
    {L'қ', "kh"},
    {L'Ң', "NG"},
    {L'ң', "ng"},
    {L'Ү', "UE"},
    {L'ү', "ue"},
    {L'Ұ', "U"},
    {L'ұ', "u"},
    {L'Һ', "H"},
    {L'һ', "h"},
    {L'Ә', "AE"},
    {L'ә', "ae"},
    {L'Ө', "OE"},
    {L'ө', "oe"},
    {L'Ա', "A"},
    {L'Բ', "B"},
    {L'Գ', "G"},
    {L'Դ', "D"},
    {L'Ե', "E"},
    {L'Զ', "Z"},
    {L'Է', "E'"},
    {L'Ը', "Y'"},
    {L'Թ', "T'"},
    {L'Ժ', "JH"},
    {L'Ի', "I"},
    {L'Լ', "L"},
    {L'Խ', "X"},
    {L'Ծ', "C'"},
    {L'Կ', "K"},
    {L'Հ', "H"},
    {L'Ձ', "D'"},
    {L'Ղ', "GH"},
    {L'Ճ', "TW"},
    {L'Մ', "M"},
    {L'Յ', "Y"},
    {L'Ն', "N"},
    {L'Շ', "SH"},
    {L'Չ', "CH"},
    {L'Պ', "P"},
    {L'Ջ', "J"},
    {L'Ռ', "R'"},
    {L'Ս', "S"},
    {L'Վ', "V"},
    {L'Տ', "T"},
    {L'Ր', "R"},
    {L'Ց', "C"},
    {L'Փ', "P'"},
    {L'Ք', "Q'"},
    {L'Օ', "O''"},
    {L'Ֆ', "F"},
    {L'և', "EV"},
    {L'ء', "a"},
    {L'آ', "aa"},
    {L'أ', "a"},
    {L'ؤ', "u"},
    {L'إ', "i"},
    {L'ئ', "e"},
    {L'ا', "a"},
    {L'ب', "b"},
    {L'ة', "h"},
    {L'ت', "t"},
    {L'ث', "th"},
    {L'ج', "j"},
    {L'ح', "h"},
    {L'خ', "kh"},
    {L'د', "d"},
    {L'ذ', "th"},
    {L'ر', "r"},
    {L'ز', "z"},
    {L'س', "s"},
    {L'ش', "sh"},
    {L'ص', "s"},
    {L'ض', "dh"},
    {L'ط', "t"},
    {L'ظ', "z"},
    {L'ع', "a"},
    {L'غ', "gh"},
    {L'ف', "f"},
    {L'ق', "q"},
    {L'ك', "k"},
    {L'ل', "l"},
    {L'م', "m"},
    {L'ن', "n"},
    {L'ه', "h"},
    {L'و', "w"},
    {L'ى', "a"},
    {L'ي', "y"},
    {L'ً', "an"},
    {L'ٌ', "on"},
    {L'ٍ', "en"},
    {L'َ', "a"},
    {L'ُ', "u"},
    {L'ِ', "e"},
    {L'ْ', ""},
    {L'٠', "0"},
    {L'١', "1"},
    {L'٢', "2"},
    {L'٣', "3"},
    {L'٤', "4"},
    {L'٥', "5"},
    {L'٦', "6"},
    {L'٧', "7"},
    {L'٨', "8"},
    {L'٩', "9"},
    {L'پ', "p"},
    {L'چ', "ch"},
    {L'ژ', "zh"},
    {L'ک', "k"},
    {L'گ', "g"},
    {L'ی', "y"},
    {L'۰', "0"},
    {L'۱', "1"},
    {L'۲', "2"},
    {L'۳', "3"},
    {L'۴', "4"},
    {L'۵', "5"},
    {L'۶', "6"},
    {L'۷', "7"},
    {L'۸', "8"},
    {L'۹', "9"},
    {L'฿', "baht"},
    {L'ა', "a"},
    {L'ბ', "b"},
    {L'გ', "g"},
    {L'დ', "d"},
    {L'ე', "e"},
    {L'ვ', "v"},
    {L'ზ', "z"},
    {L'თ', "t"},
    {L'ი', "i"},
    {L'კ', "k"},
    {L'ლ', "l"},
    {L'მ', "m"},
    {L'ნ', "n"},
    {L'ო', "o"},
    {L'პ', "p"},
    {L'ჟ', "zh"},
    {L'რ', "r"},
    {L'ს', "s"},
    {L'ტ', "t"},
    {L'უ', "u"},
    {L'ფ', "f"},
    {L'ქ', "k"},
    {L'ღ', "gh"},
    {L'ყ', "q"},
    {L'შ', "sh"},
    {L'ჩ', "ch"},
    {L'ც', "ts"},
    {L'ძ', "dz"},
    {L'წ', "ts"},
    {L'ჭ', "ch"},
    {L'ხ', "kh"},
    {L'ჯ', "j"},
    {L'ჰ', "h"},
    {L'Ṣ', "S"},
    {L'ṣ', "s"},
    {L'Ẁ', "W"},
    {L'ẁ', "w"},
    {L'Ẃ', "W"},
    {L'ẃ', "w"},
    {L'Ẅ', "W"},
    {L'ẅ', "w"},
    {L'ẞ', "SS"},
    {L'Ạ', "A"},
    {L'ạ', "a"},
    {L'Ả', "A"},
    {L'ả', "a"},
    {L'Ấ', "A"},
    {L'ấ', "a"},
    {L'Ầ', "A"},
    {L'ầ', "a"},
    {L'Ẩ', "A"},
    {L'ẩ', "a"},
    {L'Ẫ', "A"},
    {L'ẫ', "a"},
    {L'Ậ', "A"},
    {L'ậ', "a"},
    {L'Ắ', "A"},
    {L'ắ', "a"},
    {L'Ằ', "A"},
    {L'ằ', "a"},
    {L'Ẳ', "A"},
    {L'ẳ', "a"},
    {L'Ẵ', "A"},
    {L'ẵ', "a"},
    {L'Ặ', "A"},
    {L'ặ', "a"},
    {L'Ẹ', "E"},
    {L'ẹ', "e"},
    {L'Ẻ', "E"},
    {L'ẻ', "e"},
    {L'Ẽ', "E"},
    {L'ẽ', "e"},
    {L'Ế', "E"},
    {L'ế', "e"},
    {L'Ề', "E"},
    {L'ề', "e"},
    {L'Ể', "E"},
    {L'ể', "e"},
    {L'Ễ', "E"},
    {L'ễ', "e"},
    {L'Ệ', "E"},
    {L'ệ', "e"},
    {L'Ỉ', "I"},
    {L'ỉ', "i"},
    {L'Ị', "I"},
    {L'ị', "i"},
    {L'Ọ', "O"},
    {L'ọ', "o"},
    {L'Ỏ', "O"},
    {L'ỏ', "o"},
    {L'Ố', "O"},
    {L'ố', "o"},
    {L'Ồ', "O"},
    {L'ồ', "o"},
    {L'Ổ', "O"},
    {L'ổ', "o"},
    {L'Ỗ', "O"},
    {L'ỗ', "o"},
    {L'Ộ', "O"},
    {L'ộ', "o"},
    {L'Ớ', "O"},
    {L'ớ', "o"},
    {L'Ờ', "O"},
    {L'ờ', "o"},
    {L'Ở', "O"},
    {L'ở', "o"},
    {L'Ỡ', "O"},
    {L'ỡ', "o"},
    {L'Ợ', "O"},
    {L'ợ', "o"},
    {L'Ụ', "U"},
    {L'ụ', "u"},
    {L'Ủ', "U"},
    {L'ủ', "u"},
    {L'Ứ', "U"},
    {L'ứ', "u"},
    {L'Ừ', "U"},
    {L'ừ', "u"},
    {L'Ử', "U"},
    {L'ử', "u"},
    {L'Ữ', "U"},
    {L'ữ', "u"},
    {L'Ự', "U"},
    {L'ự', "u"},
    {L'Ỳ', "Y"},
    {L'ỳ', "y"},
    {L'Ỵ', "Y"},
    {L'ỵ', "y"},
    {L'Ỷ', "Y"},
    {L'ỷ', "y"},
    {L'Ỹ', "Y"},
    {L'ỹ', "y"},
    {L'–', "-"},
    {L'‘', "'"},
    {L'’', "'"},
    {L'“', "\""},
    {L'”', "\""},
    {L'„', "\""},
    {L'†', "+"},
    {L'•', "*"},
    {L'…', "..."},
    {L'₠', "ecu"},
    {L'₢', "cruzeiro"},
    {L'₣', "french franc"},
    {L'₤', "lira"},
    {L'₥', "mill"},
    {L'₦', "naira"},
    {L'₧', "peseta"},
    {L'₨', "rupee"},
    {L'₩', "won"},
    {L'₪', "new shequel"},
    {L'₫', "dong"},
    {L'€', "euro"},
    {L'₭', "kip"},
    {L'₮', "tugrik"},
    {L'₯', "drachma"},
    {L'₰', "penny"},
    {L'₱', "peso"},
    {L'₲', "guarani"},
    {L'₳', "austral"},
    {L'₴', "hryvnia"},
    {L'₵', "cedi"},
    {L'₸', "kazakhstani tenge"},
    {L'₹', "indian rupee"},
    {L'₺', "turkish lira"},
    {L'₽', "russian ruble"},
    {L'₿', "bitcoin"},
    {L'℠', "sm"},
    {L'™', "tm"},
    {L'∂', "d"},
    {L'∆', "delta"},
    {L'∑', "sum"},
    {L'∞', "infinity"},
    {L'♥', "love"},
    {L'元', "yuan"},
    {L'円', "yen"},
    {L'﷼', "rial"},
    {L'ﻵ', "laa"},
    {L'ﻷ', "laa"},
    {L'ﻹ', "lai"},
    {L'ﻻ', "la"},
};

static const Locale locales[MAX_LOCALES] = {
    {"bg",
     {
         {L'Й', "Y"},
         {L'Ц', "Ts"},
         {L'Щ', "Sht"},
         {L'Ъ', "A"},
         {L'Ь', "Y"},
         {L'й', "y"},
         {L'ц', "ts"},
         {L'щ', "sht"},
         {L'ъ', "a"},
         {L'ь', "y"},
     },
     10},
    {"de",
     {
         {L'Ä', "AE"},
         {L'ä', "ae"},
         {L'Ö', "OE"},
         {L'ö', "oe"},
         {L'Ü', "UE"},
         {L'ü', "ue"},
         {L'ß', "ss"},
         {L'%', "prozent"},
         {L'&', "und"},
         {L'|', "oder"},
         {L'∑', "summe"},
         {L'∞', "unendlich"},
         {L'♥', "liebe"},
     },
     13},
    {"es",
     {
         {L'%', "por ciento"},
         {L'&', "y"},
         {L'<', "menor que"},
         {L'>', "mayor que"},
         {L'|', "o"},
         {L'¢', "centavos"},
         {L'£', "libras"},
         {L'¤', "moneda"},
         {L'₣', "francos"},
         {L'∑', "suma"},
         {L'∞', "infinito"},
         {L'♥', "amor"},
     },
     12},
    {"fr",
     {
         {L'%', "pourcent"},
         {L'&', "et"},
         {L'<', "plus petit"},
         {L'>', "plus grand"},
         {L'|', "ou"},
         {L'¢', "centime"},
         {L'£', "livre"},
         {L'¤', "devise"},
         {L'₣', "franc"},
         {L'∑', "somme"},
         {L'∞', "infini"},
         {L'♥', "amour"},
     },
     12},
    {"pt",
     {
         {L'%', "porcento"},
         {L'&', "e"},
         {L'<', "menor"},
         {L'>', "maior"},
         {L'|', "ou"},
         {L'¢', "centavo"},
         {L'∑', "soma"},
         {L'£', "libra"},
         {L'∞', "infinito"},
         {L'♥', "amor"},
     },
     10},
    {"uk",
     {
         {L'И', "Y"},
         {L'и', "y"},
         {L'Й', "Y"},
         {L'й', "y"},
         {L'Ц', "Ts"},
         {L'ц', "ts"},
         {L'Х', "Kh"},
         {L'х', "kh"},
         {L'Щ', "Shch"},
         {L'щ', "shch"},
         {L'Г', "H"},
         {L'г', "h"},
     },
     12},
    {"vi",
     {
         {L'Đ', "D"},
         {L'đ', "d"},
     },
     2},
    {"da",
     {
         {L'Ø', "OE"},
         {L'ø', "oe"},
         {L'Å', "AA"},
         {L'å', "aa"},
         {L'%', "procent"},
         {L'&', "og"},
         {L'|', "eller"},
         {L'$', "dollar"},
         {L'<', "mindre end"},
         {L'>', "større end"},
     },
     10},
    {"nb",
     {
         {L'&', "og"},
         {L'Å', "AA"},
         {L'Æ', "AE"},
         {L'Ø', "OE"},
         {L'å', "aa"},
         {L'æ', "ae"},
         {L'ø', "oe"},
     },
     7},
    {"it",
     {
         {L'&', "e"},
     },
     1},
    {"nl",
     {
         {L'&', "en"},
     },
     1},
    {"sv",
     {
         {L'&', "och"},
         {L'Å', "AA"},
         {L'Ä', "AE"},
         {L'Ö', "OE"},
         {L'å', "aa"},
         {L'ä', "ae"},
         {L'ö', "oe"},
     },
     7},
};

static const char *lookup_char_map(wchar_t ch) {
  for (int i = 0; i < MAX_CHAR_MAP; ++i) {
    if (charMap[i].value == NULL) {
      break;
    }
    if (charMap[i].key == ch) {
      return charMap[i].value;
    }
  }
  return NULL;
}

static const char *lookup_locale_map(const char *locale, wchar_t ch) {
  for (int i = 0; i < MAX_LOCALES; ++i) {
    if (locales[i].locale == NULL) {
      break;
    }
    if (strcmp(locales[i].locale, locale) == 0) {
      for (int j = 0; j < locales[i].size; ++j) {
        if (locales[i].entries[j].key == ch) {
          return locales[i].entries[j].value;
        }
      }
    }
  }
  return NULL;
}

void slugify(const wchar_t *input, char *output,
             const SlugifyOptions *options) {
  const wchar_t *remove_set =
      options->remove ? options->remove : DEFAULT_REMOVE;
  char replacement = options->replacement;
  bool trim = options->trim;
  int len = wcslen(input);
  int out_index = 0;
  wchar_t buffer[MAX_BUFFER_SIZE];

  for (int i = 0; i < len && out_index < MAX_BUFFER_SIZE - 1; ++i) {
    const char *mapped = NULL;
    if (options->locale) {
      mapped = lookup_locale_map(options->locale, input[i]);
    }
    if (!mapped) {
      mapped = lookup_char_map(input[i]);
    }
    if (!mapped) {
      buffer[out_index++] = input[i];
    } else {
      while (*mapped && out_index < MAX_BUFFER_SIZE - 1) {
        buffer[out_index++] = *mapped++;
      }
    }
  }
  buffer[out_index] = L'\0';

  out_index = 0;
  int len_buffer = wcslen(buffer);
  int in_space = 0;

  int start = 0;
  int end = len_buffer;

  if (trim) {
    while (start < len_buffer &&
           (buffer[start] == L' ' || buffer[start] == replacement)) {
      start++;
    }
    while (end > start &&
           (buffer[end - 1] == L' ' || buffer[end - 1] == replacement)) {
      end--;
    }
  }

  for (int i = start; i < end && out_index < MAX_BUFFER_SIZE - 1; ++i) {
    wchar_t ch = buffer[i];
    if (wcschr(remove_set, ch)) {
      continue;
    }
    if (ch == L' ' || ch == replacement) {
      if (!in_space) {
        output[out_index++] = replacement;
        in_space = 1;
      }
    } else {
      if (options->strict && !iswalnum(ch)) {
        continue;
      }
      output[out_index++] = options->lower ? towlower(ch) : ch;
      in_space = 0;
    }
  }

  if (!trim) {
    if (start > 0) {
      memmove(output + 1, output, out_index);
      output[0] = replacement;
      out_index++;
    }
    if (end < len_buffer) {
      output[out_index++] = replacement;
    }
  }

  if (trim && out_index > 0 && output[out_index - 1] == replacement) {
    out_index--;
  }
  output[out_index] = '\0';
}
